name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [12, 14]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}

    - name: (env) pnpm
      run: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm

    - name: (env) cache
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ matrix.nodejs }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-${{ matrix.nodejs }}-

    - name: Install
      run: pnpm install

    - name: Run Tests
      run: pnpm test

    - name: Check Types
      run: pnpm run types

    - name: Compiles
      run: pnpm run build
