name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [12, 14]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}

    - name: (env) pnpm
      run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node

    - name: (env) cache
      uses: actions/cache@master
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

    - name: Install
      run: pnpm install

    - name: Run Tests
      run: pnpm test

    - name: Check Types
      run: pnpm run types

    - name: Compiles
      run: pnpm run build
